### ISSUE TITLE
Support for Other Data Types

### ISSUE THREAD

**Issue by RyannDaGreat** [cielong/pyfx#68]
Could we add support for non-json objects? An example of a working implementation can be found in the python debugger tui called "pudb", in their variable explorer. 
My use case is exploring the contents of pytorch checkpoints (.pth files), which when loaded are nested OrderedDicts (which are not dicts) and also contain torch tensors (a lot like numpy arrays, which are much like lists). Is there a way to add support for custom datatypes like these in my application?
Thank you,
Ryan

**Comment by cielong** [comment]
Hi Ryan, 

Thanks for reaching out. 

I think the JSON libs I write do support custom data types (see https://github.com/cielong/pyfx/blob/8c7ad55854a4f8cc59efa9f770b07f64522187e6/src/pyfx/view/json_lib/node_factory.py#L14 and https://github.com/cielong/pyfx/blob/8c7ad55854a4f8cc59efa9f770b07f64522187e6/tests/unit_tests/view/json-lib/test_node_factory.py#L51), but it seems I did not surface it to the application level. 

Let me think about how I can provide a more extensible way for this. 

Thanks,
Yutian

**Comment by RyannDaGreat** [comment]
Thank you! I look forward to it:) 
Would you be inerested in PR's that enable numpy arrays, torch tensors and ordered dicts out of the box? (Or perhaps a more general solution?)

**Comment by cielong** [comment]
Feel free to submit PR. While I like a more general solution for this, but out of box support for those is acceptable, we can always refactor if there's a better solution later.

In the end, this is an experimental project for me :) It's great to hear it can help someone

**Comment by cielong** [comment]
Actually, the model part is implemented in the mind that JSON is the input. So the change may be more non-trivial as I previously thought.

**Comment by RyannDaGreat** [comment]
Hi @cielong , I'm about to create a pull request that allows pyfx to handle many new datatypes such as OrderedDict, numpy.ndarray, torch.Tensor, bytes, bytearray, tuple, pandas.DataFrame, etc etc. I've also made a youtube video explaining what changes I made and why: https://www.youtube.com/watch?v=GBsXna6Ynqw
